/**
 * @file SchedulerEvents.ts
 * @description Event constants for the Process Scheduler.
 */

export const SCHEDULER_EVENT_NAMES = {
  SCHEDULER_STARTED: 'SCHEDULER_STARTED',
  SCHEDULER_STOPPED: 'SCHEDULER_STOPPED',
  SCHEDULER_PAUSED: 'SCHEDULER_PAUSED',
  SCHEDULER_RESUMED: 'SCHEDULER_RESUMED',
  SCHEDULER_ERROR: 'SCHEDULER_ERROR',
  PROCESS_SCHEDULED: 'PROCESS_SCHEDULED',
  PROCESS_PREEMPTED: 'PROCESS_PREEMPTED',
  PROCESS_COMPLETED: 'PROCESS_COMPLETED',
  PROCESS_PRIORITY_CHANGED: 'PROCESS_PRIORITY_CHANGED',
} as const;
