/**
 * @file ShellEvents.ts
 * @description Event constants for the Shell subsystem.
 */

export const SHELL_EVENT_NAMES = {
  SHELL_STARTED: 'SHELL_STARTED',
  SHELL_STOPPED: 'SHELL_STOPPED',
  SHELL_SESSION_CREATED: 'SHELL_SESSION_CREATED',
  SHELL_SESSION_CLOSED: 'SHELL_SESSION_CLOSED',
  COMMAND_STARTED: 'COMMAND_STARTED',
  COMMAND_COMPLETED: 'COMMAND_COMPLETED',
  COMMAND_FAILED: 'COMMAND_FAILED',
} as const;
