declare module 'lucide-react' {
  import * as React from 'react';
  export type LucideIcon = React.ForwardRefExoticComponent<
    React.SVGProps<SVGSVGElement> & {
      color?: string;
      size?: string | number;
      strokeWidth?: string | number;
      absoluteStrokeWidth?: boolean;
    } & React.RefAttributes<SVGSVGElement>
  >;

  export const Home: LucideIcon;
  export const Code: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const Folder: LucideIcon;
  export const FolderOpen: LucideIcon;
  export const FolderPlus: LucideIcon;
  export const File: LucideIcon;
  export const FileText: LucideIcon;
  export const FilePlus: LucideIcon;
  export const Settings: LucideIcon;
  export const Terminal: LucideIcon;
  export const Globe: LucideIcon;
  export const Image: LucideIcon;
  export const Music: LucideIcon;
  export const Video: LucideIcon;
  export const Trash2: LucideIcon;
  export const Search: LucideIcon;
  export const Plus: LucideIcon;
  export const X: LucideIcon;
  export const Minus: LucideIcon;
  export const Square: LucideIcon;
  export const Copy: LucideIcon;
  export const Scissors: LucideIcon;
  export const Clipboard: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const Grid: LucideIcon;
  export const List: LucideIcon;
  export const Star: LucideIcon;
  export const Clock: LucideIcon;
  export const Edit: LucideIcon;
  export const Info: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUp: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const Check: LucideIcon;
  export const Pin: LucideIcon;
  export const Archive: LucideIcon;
  export const Tag: LucideIcon;
  export const Save: LucideIcon;
  export const Bold: LucideIcon;
  export const Italic: LucideIcon;
  export const Underline: LucideIcon;
  export const Strikethrough: LucideIcon;
  export const AlignLeft: LucideIcon;
  export const AlignCenter: LucideIcon;
  export const AlignRight: LucideIcon;
  export const AlignJustify: LucideIcon;
  export const ListOrdered: LucideIcon;
  export const Table: LucideIcon;
  export const Undo: LucideIcon;
  export const Redo: LucideIcon;
  export const Monitor: LucideIcon;
  export const Activity: LucideIcon;
  export const Calculator: LucideIcon;
  export const RotateCw: LucideIcon;
  export const Palette: LucideIcon;
  export const Rocket: LucideIcon;
  export const LayoutGrid: LucideIcon;
  export const Play: LucideIcon;
  export const Lock: LucideIcon;
  export const LogOut: LucideIcon;
  export const RotateCcw: LucideIcon;
  export const Power: LucideIcon;
  export const User: LucideIcon;
  export const Wifi: LucideIcon;
  export const Volume2: LucideIcon;
  export const VolumeX: LucideIcon;
  export const BatteryCharging: LucideIcon;
  export const Bell: LucideIcon;
  export const PinOff: LucideIcon;
  export const Layers: LucideIcon;
  export const Maximize2: LucideIcon;
  export const Minimize2: LucideIcon;
  export const Heading1: LucideIcon;
  export const Heading2: LucideIcon;
  export const CheckSquare: LucideIcon;
  export const History: LucideIcon;
  export const Eye: LucideIcon;
  export const Download: LucideIcon;
  export const Edit2: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const Replace: LucideIcon;
  export const ReplaceAll: LucideIcon;
  export const HardDrive: LucideIcon;
  export const Sliders: LucideIcon;

  const content: Record<string, LucideIcon>;
  export default content;
}
